### PR TITLE
Fixing problem with null pointers.

### LINKED ISSUE #251: Constraint definition with empty fields results in null-pointer-exception.
grafik
This constraint definition results in a null-pointer-exception and the backend doesn't return a ParsingResponse.

### PR DESCRIPTION
**Pull request by marcelfloe**
closes #251

### CODE REVIEW

File: server/src/main/java/de/uftos/repositories/ucdl/parser/UcdlParser.java [hunk 1]
```diff
@@ -67,6 +68,14 @@ private static ConstraintDefinitionDto parseConstraintDefinition(String name,
 
     String description = constraintDefinition.get("description").textValue();
 
+    if (description == null) {
+      throw new ParseException("The description needs to contain a String!");
+    }
+
+    if (description.replaceAll("\\s", "").isEmpty()) {
+      throw new ParseException("The description requires a non-whitespace text!");
+    }
```
Comment (danieldietzler) [inline server/src/main/java/de/uftos/repositories/ucdl/parser/UcdlParser.java:77]: Isn't there something like `isBlank`?

**Review by danieldietzler — APPROVED** [review]
Nice!

File: server/src/main/java/de/uftos/repositories/ucdl/parser/UcdlParser.java (hunk 1 above)
Comment (danieldietzler) [reply server/src/main/java/de/uftos/repositories/ucdl/parser/UcdlParser.java:77]: @marcelfloe ah yes https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/lang/String.html#isBlank()
